### ISSUE TITLE
Board restarts twice when uploading while monitoring

### ISSUE THREAD

**Issue by OoDeLally** [gepd/Deviot#257] opened 2018-08-17 14:41 UTC
### Operating system
Linux Mint + ST3

### Board used
Arduino Uno

### Description of problem
When hitting the `Upload` button, it recompiles, uploads and reset the board. This is great.
If we do that while monitoring is enabled, the board is restarted twice: 
1- The program runs for around ~0.5sec and is immediately aborted after this short delay.
2- Then immediately reset again. This time the program runs for good.

### Error(s) in ST Console? (View > Show Console)
The sublime console displays

```reloading settings Packages/User/deviot.sublime-settings```

at the moment i press the `Upload` command, and then displays a second time

```reloading settings Packages/User/deviot.sublime-settings```

when the fake (first) run starts.
It doesnt print anything when the real run (second) starts.

### Steps to Reproduce
Do as described in the problem description. This works for any program.

### Actual Results
It seems that the board is reset twice at a ~0.5sec interval.

### Expected Results
The board should be reset only once after the upload.

### Additional info
It only happens when the monitoring (`Monitor Serial -> Start monitor`) is enable.

I made a little video of the sequence: https://youtu.be/a9Xvauyfsqo
**Add english subtitles to read the comment about what i'm doing while filming.**
The blue led indicates setup phase. The green led indicates run phase.

**Comment by gepd** [comment] 2018-08-19 20:41
`reloading settings Packages/User/deviot.sublime-settings` doesn't mean the board is reset twice, the reason is when you have the Serial Monitor running, the plugin stores that state and save it in a file, each time that file is writed ST log that change in the console (`reloading settings Packages/User/deviot.sublime-settings`) There are others changes happening in background so sometimes will see it more than twice but there is nothing to worry about it

**Comment by OoDeLally** [comment] 2018-09-13 13:09
I see. This was just an observation, and I did not know whether it was correlated. Thanks for the info.
The problem is still there. Do you have any insight?

**Comment by gepd** [comment] 2019-02-17 04:44
I'll close this as it's not a bug

**Closed by gepd** 2019-02-17 04:44 UTC
Labels: wontfix
