### ISSUE TITLE
Portable Sublime and Python

### ISSUE THREAD

**Issue by eusebiotebar** [gepd/Deviot#38] opened 2016-07-06 08:04 UTC
Hi
MY SETUP:
I'm running a portable version of Python 2.7.6.1 (http://portablepython.com/wiki/PortablePython2.7.6.1/ ) on a USB stick, installed under: "E:\MyTools\Python\App"

Also, I'm running a portable version of Sublime Text 3 Build 3059 (http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203059.zip ) on the same USB stick, installed under: "E:\MyTools\Sublime Text 3\"

Edited the "E:\MyTools\Sublime Text 3\Data\Packages\Deviot\Settings-Default\Deviot Preferences.sublime-settings" with this line:
"env_path": "E:\\MyTools\\Python\\App","E:\\MyTools\\Python\\App\\Scripts"

Results:
When Sublime stars, Devion ask again for instal python 2.7

Any idea for setting?

**Comment by gepd** [comment] 2016-07-07 01:02
HI @eusebiotebar 

I've added a fix for this issue. Please overwrite the file `Packages/Deviot/libs/Install.py` for [this](https://www.dropbox.com/s/i9wq5gmst1ox2a9/Install.py?dl=0) one

And sets the env_path var in this way: 
`"env_path": "E:\\MyTools\\Python\\App;E:\\MyTools\\Python\\App\\Scripts"`

It should fix the problem

**Comment by eusebiotebar** [comment] 2016-07-07 08:20
Same result

Output from console
================
C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
================

**Comment by gepd** [comment] 2016-07-07 08:44
I'm Sorry I just realized now you are editing the wrong file, the `Deviot Preferences.sublime-settings` is located in: `E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot`

The file should looks like this:

```
{
    "env_path": "E:\\MyTools\\Python\\App;E:\\MyTools\\Python\\App\\Scripts", 
    "id_lang": "en"
}
```

**Comment by eusebiotebar** [comment] 2016-07-07 09:17
It works.... more or less :100:.. I mean that now it tries to install PlatformIO but after a while, the installation says 

`Error Creating the virtualenv` 

I don't think so it is a problem from Deviot but a PlatformIO issue. Probably it tries to install it over the hard disk (which I don't have the proper rights) instead the 'portable' disk.

**Comment by gepd** [comment] 2016-07-07 09:28
It may be a permission issue, can you see if the console shows any aditional information? (and paste here)

Can't you run ST as administrator?

**Comment by eusebiotebar** [comment] 2016-07-07 09:39
I can't run ST as admin in this computer. I will try this afternoon at home.

The only output from consoly is this:
`[ Deviot 1.1.10 ] Instalación`
`11:36:39 PlatformIO no está instalado`
`Preparándose para instalarlo. Por favor sea paciente esto podría demorar un poco`
`11:36:39 Extrayendo archivos...`
`11:36:39 Instalando PlatformIO...`
`11:37:07 Error Creating the virtualenv`

**Comment by gepd** [comment] 2016-07-07 09:51
The ST console can show extra information `ST Menu View > Show Console` it's different from deviot console

**Comment by eusebiotebar** [comment] 2016-07-07 10:12
My mistake, I was thinking that the output was from ST console.

This is the ST console Output. 

```
================
""E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\pio"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Package Control: Skipping automatic upgrade, last run at 2016-07-07 11:36:49, next run at 2016-07-07 12:36:49 or after
New python executable in E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe
ERROR: The executable "E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe" could not be run: [Error 5] Acceso denegado
```


It seems that I should have admin rights, but I can execute from external the command
`"E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe" `

**Comment by eusebiotebar** [comment] 2016-07-11 05:52
The same result and console output in a personal home computer.

**Comment by gepd** [comment] 2016-07-11 18:33
It's possible we can schedule a teamviewer meeting so I can debug this problem? you can write me to get@outlook.com

**Comment by eusebiotebar** [comment] 2016-07-14 12:04
The error message says:
`New python executable in E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe`
`ERROR: The executable "E:\MyTools\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe"`

So in some part you do copy for `python.exe` in that folder, why?

**Comment by gepd** [comment] 2016-07-15 01:52
To install platformio, the core of deviot, the plugin creates a virtual environment. The virtual environment install python inside of that folder. All that, is to install deviot and the dependencies automatically.

**Comment by asrimane** [comment] 2016-07-30 18:43
Hi, 
I have the same error:

`New python executable in C:\Users\***\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts\python.exe`
`ERROR: The executable "C:\Users\***\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts\python.exe" could not be run: [Error 5] Accès refus`


what is the script that runs the executable `Deviot\penv\Scripts\python.exe` ?
I want to try to copy it somewhere else.
The problem does not come from the apparently antivirus

@+

**Comment by gepd** [comment] 2016-07-30 19:35
The whole plugin uses that executable, I've tried to reproduce this issue but I can't, are you using Windows 10 too?

One command can be

`C:\Users\***\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts\python --version`
or
`C:\Users\***\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts\pio --version`

If you want we can check this by Teamviewer
you can contactme at gepd@outlook.com

**Comment by asrimane** [comment] 2016-07-31 02:12
No i have Windows 8.1 64bit

**Comment by gepd** [comment] 2016-08-01 10:43
I'm sorry, as I can't replicate this issue isn't much I can do by now

**Comment by gepd** [comment] 2016-09-27 16:47
Re open this issue if you have new information or if you are willing to arrange a meeting with me in teamviewer or something similar.

**Closed by gepd** 2016-09-27 16:47 UTC
Labels: help wanted
